//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingFirms
    {
        public int AF_ID { get; set; }
        public string AF_CID { get; set; }
        public string AF_Name { get; set; }
        public string AF_Logo { get; set; }
        public int AF_Type { get; set; }
        public string AF_Address { get; set; }
        public string Contact { get; set; }
        public string Telphone { get; set; }
        public string TaxpayerID { get; set; }
        public string RegistrationAddress { get; set; }
        public string AF_Bank { get; set; }
        public string AF_BankAccount { get; set; }
    }
}
