//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_User
    {
        public int User_ID { get; set; }
        public int AF_ID { get; set; }
        public int Org_ID { get; set; }
        public string User_Name { get; set; }
        public string Photo { get; set; }
        public string Login_Name { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> P_ID { get; set; }
        public Nullable<int> Sex { get; set; }
        public string TelPhone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public byte[] LockVersion { get; set; }
    }
}
