//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_OperatingLog
    {
        public long OL_ID { get; set; }
        public Nullable<int> AF_ID { get; set; }
        public int User_ID { get; set; }
        public string Modules { get; set; }
        public string OperatingType { get; set; }
        public string OperatingInstructions { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
