//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Contract
    {
        public long C_COID { get; set; }
        public string FirstSubjectCode { get; set; }
        public string FirstSubjectTitle { get; set; }
        public string SubjectCode { get; set; }
        public string HelpCode { get; set; }
        public string SubjectTitle { get; set; }
        public Nullable<int> C_ID { get; set; }
        public Nullable<int> CFRE_ER { get; set; }
        public Nullable<int> ContractType { get; set; }
        public string ContractID { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public Nullable<int> Number { get; set; }
        public string HandleDepartment { get; set; }
        public string Handler { get; set; }
        public Nullable<int> isInvoice { get; set; }
        public Nullable<int> isOver { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Attachment { get; set; }
    }
}
