//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FinancialRelevanceEnterprise
    {
        public long CFRE_ID { get; set; }
        public Nullable<int> CFRE_Classify { get; set; }
        public Nullable<long> CFR_ID { get; set; }
        public Nullable<int> CFRE_ER { get; set; }
        public string FirstSubjectCode { get; set; }
        public string FirstSubjectTitle { get; set; }
        public string SubjectCode { get; set; }
        public string HelpCode { get; set; }
        public string SubjectTitle { get; set; }
    }
}
