//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RelevancePersonage
    {
        public long CRP_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_Type { get; set; }
        public string ID { get; set; }
        public string Address { get; set; }
        public string Telphone { get; set; }
        public string PostCode { get; set; }
        public string EMail { get; set; }
        public string FundNature { get; set; }
        public Nullable<int> FundWay { get; set; }
    }
}
