//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RelevanceEnterprise
    {
        public long CRE_ID { get; set; }
        public int C_ID { get; set; }
        public Nullable<int> CRE_Classify { get; set; }
        public string CreditCode { get; set; }
        public string CN_Enterprise_Name { get; set; }
        public string EN_Enterprise_Name { get; set; }
        public Nullable<int> RegistrationMoney { get; set; }
        public string Corporation { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string RegistrationAddress { get; set; }
        public string WorkAddress { get; set; }
        public string Telphone { get; set; }
        public string Contact { get; set; }
        public byte[] Contact_Department { get; set; }
        public string Contact_Post { get; set; }
        public string Contact_Address { get; set; }
        public string Contact_Telphone { get; set; }
        public string Contact_PostCode { get; set; }
        public string FAX { get; set; }
        public string EMail { get; set; }
        public string BusinessScope { get; set; }
        public string Company_Articles { get; set; }
        public string Invoice_CompayName { get; set; }
        public string Invoice_TaxpayerID { get; set; }
        public string Invoice_TEL { get; set; }
        public string Invoice_RegistrationAddress { get; set; }
        public string Invoice_Bank { get; set; }
        public string Invoice_BankAccount { get; set; }
        public Nullable<int> isAffiliatedPerson { get; set; }
        public Nullable<int> isAffiliatedCompany { get; set; }
        public Nullable<int> BusinessType { get; set; }
        public byte[] LockVersion { get; set; }
    }
}
