//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int C_ID { get; set; }
        public string CreditCode { get; set; }
        public string CN_Compant_Name { get; set; }
        public string EN_Compant_Name { get; set; }
        public string Logo { get; set; }
        public string Company_Lever { get; set; }
        public string RegistrationCode { get; set; }
        public string OrganizationCode { get; set; }
        public string TaxpayerID { get; set; }
        public string Corporation { get; set; }
        public string Corporation_ID { get; set; }
        public int Company_Type { get; set; }
        public int Industry { get; set; }
        public string EnterpriseLabels { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> OperationPeriod { get; set; }
        public string RegInstitute { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string RegistrationMoney { get; set; }
        public string RegistrationAddress { get; set; }
        public string WorkAddress { get; set; }
        public Nullable<int> RegistrationStatus { get; set; }
        public string Telphone { get; set; }
        public string FAX { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Company_Introduction { get; set; }
        public string BusinessScope { get; set; }
        public string Company_Articles { get; set; }
        public Nullable<int> Parent_C_ID { get; set; }
        public string Parent_C_Name { get; set; }
        public string Parent_C_CreditCode { get; set; }
        public Nullable<int> AuditStatus { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public byte[] LockVersion { get; set; }
    }
}
