//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_AccountBook
    {
        public int FAB_ID { get; set; }
        public string AB_Name { get; set; }
        public Nullable<int> C_ID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> AccountingPeriod { get; set; }
        public string AccountingperiodRemark { get; set; }
        public Nullable<int> FS_ID { get; set; }
        public Nullable<int> Author { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ExportLocking { get; set; }
    }
}
