//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_DetailHelp
    {
        public int FDH_ID { get; set; }
        public Nullable<int> FAB_ID { get; set; }
        public Nullable<int> FDA_ID { get; set; }
        public Nullable<int> C_ID { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
    }
}
