//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_DetailAccount
    {
        public int FDA_ID { get; set; }
        public int C_ID { get; set; }
        public int FAB_ID { get; set; }
        public int Year { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Voucher { get; set; }
        public string VoucherID { get; set; }
        public string SubjectCode { get; set; }
        public string SubjectTitle { get; set; }
        public string Abstract { get; set; }
        public Nullable<int> Direction { get; set; }
        public Nullable<int> Number { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Money { get; set; }
        public Nullable<double> ForeignMoney { get; set; }
        public Nullable<int> ChangeRange { get; set; }
        public Nullable<int> ChangeType { get; set; }
        public Nullable<int> IsCheck { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string SysCode { get; set; }
        public string A_DetailHelp_Code { get; set; }
        public string A_DetailHelp_Name { get; set; }
        public string B_DetailHelp_Code { get; set; }
        public string B_DetailHelp_Name { get; set; }
        public string C_DetailHelp_Code { get; set; }
        public string C_DetailHelp_Name { get; set; }
        public string D_DetailHelp_Code { get; set; }
        public string D_DetailHelp_Name { get; set; }
        public string E_DetailHelp_Code { get; set; }
        public string E_DetailHelp_Name { get; set; }
        public string F_DetailHelp_Code { get; set; }
        public string F_DetailHelp_Name { get; set; }
        public string G_DetailHelp_Code { get; set; }
        public string G_DetailHelp_Name { get; set; }
        public string H_DetailHelp_Code { get; set; }
        public string H_DetailHelp_Name { get; set; }
        public string I_DetailHelp_Code { get; set; }
        public string I_DetailHelp_Name { get; set; }
        public string J_DetailHelp_Code { get; set; }
        public string J_DetailHelp_Name { get; set; }
    }
}
