//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_TrialBalance
    {
        public int FTB_ID { get; set; }
        public int C_ID { get; set; }
        public int FAB_ID { get; set; }
        public int Year { get; set; }
        public string SubjectCode { get; set; }
        public string SubjectTitle { get; set; }
        public Nullable<int> isMappingSure { get; set; }
        public string SubjectCodeMapping { get; set; }
        public string SubjectTitleMapping { get; set; }
        public string HelpCode { get; set; }
        public string ForeignCurrency { get; set; }
        public Nullable<int> Qc_Direction { get; set; }
        public Nullable<double> Qc_old { get; set; }
        public Nullable<int> Qc_num_old { get; set; }
        public Nullable<double> Qc_Change { get; set; }
        public Nullable<int> Qc_Change_num { get; set; }
        public Nullable<double> Bq_debit_old { get; set; }
        public Nullable<int> Bq_debit_num_old { get; set; }
        public Nullable<int> Bq_debit_num { get; set; }
        public Nullable<double> Bq_debit { get; set; }
        public Nullable<double> Bq_credit_old { get; set; }
        public Nullable<int> Bq_credit_num_old { get; set; }
        public Nullable<int> Bq_credit_num { get; set; }
        public Nullable<double> Bq_credit { get; set; }
        public Nullable<int> Qm_Direction { get; set; }
        public Nullable<double> Qm_old { get; set; }
        public Nullable<int> Qm_num_old { get; set; }
        public Nullable<double> Bq_Change_credit { get; set; }
        public Nullable<int> Bq_Change_credit_num { get; set; }
        public Nullable<double> Bq_Change_debit { get; set; }
        public Nullable<int> Bq_Change_debit_num { get; set; }
        public Nullable<int> SubjectLevel { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<int> Direction { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsConfirmation { get; set; }
        public string SubjectCodePath { get; set; }
        public string SubjectTitlePath { get; set; }
        public string ParentSubjectCode { get; set; }
        public Nullable<int> IsMapping { get; set; }
    }
}
