//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FR_Report_Formula
    {
        public int FR_FRID { get; set; }
        public Nullable<int> C_ID { get; set; }
        public string FR_Code { get; set; }
        public string FR_FCode { get; set; }
        public string SubjectTitle { get; set; }
        public string Subject_File { get; set; }
        public Nullable<int> FR_RowValue { get; set; }
        public Nullable<int> Direction { get; set; }
    }
}
