//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FR_Report
    {
        public int FR_ID { get; set; }
        public string FR_Code { get; set; }
        public string FR_Name { get; set; }
        public Nullable<int> FR_Type { get; set; }
        public string FR_Content { get; set; }
    }
}
