//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BaseTable
    {
        public int MID { get; set; }
        public string Filed { get; set; }
        public Nullable<int> M_ID { get; set; }
        public string M_Name { get; set; }
    }
}
