//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuditDBEntities : DbContext
    {
        public AuditDBEntities()
            : base("name=AuditDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountingFirms> AccountingFirms { get; set; }
        public virtual DbSet<Audit_OperatingLog> Audit_OperatingLog { get; set; }
        public virtual DbSet<Audit_Organization> Audit_Organization { get; set; }
        public virtual DbSet<Audit_Post> Audit_Post { get; set; }
        public virtual DbSet<Audit_User> Audit_User { get; set; }
        public virtual DbSet<C_Bank_Account> C_Bank_Account { get; set; }
        public virtual DbSet<C_Contract> C_Contract { get; set; }
        public virtual DbSet<C_FinancialRelevanceEnterprise> C_FinancialRelevanceEnterprise { get; set; }
        public virtual DbSet<C_RelevanceEnterprise> C_RelevanceEnterprise { get; set; }
        public virtual DbSet<C_RelevancePersonage> C_RelevancePersonage { get; set; }
        public virtual DbSet<CA_Role> CA_Role { get; set; }
        public virtual DbSet<CA_User> CA_User { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<F_DetailAccount> F_DetailAccount { get; set; }
        public virtual DbSet<F_TrialBalance> F_TrialBalance { get; set; }
        public virtual DbSet<FR_Report> FR_Report { get; set; }
        public virtual DbSet<FR_Report_Formula> FR_Report_Formula { get; set; }
        public virtual DbSet<M_BaseTable> M_BaseTable { get; set; }
        public virtual DbSet<M_Subject> M_Subject { get; set; }
        public virtual DbSet<报表字段> 报表字段 { get; set; }
        public virtual DbSet<F_AccountBook> F_AccountBook { get; set; }
        public virtual DbSet<F_DetailAttachment> F_DetailAttachment { get; set; }
        public virtual DbSet<F_DetailHelp> F_DetailHelp { get; set; }
        public virtual DbSet<F_FinancialSystem> F_FinancialSystem { get; set; }
        public virtual DbSet<F_Proof> F_Proof { get; set; }
    }
}
