//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class 报表字段
    {
        public int FR_FID { get; set; }
        public string FR_FCode { get; set; }
        public string FR_FName { get; set; }
        public Nullable<int> isCustomField { get; set; }
        public Nullable<int> isConvergeField { get; set; }
    }
}
